---
# defaults file for ansible-telegraf

telegraf_agent_version: 1.9.1
telegraf_agent_version_patch: 1
telegraf_agent_package: telegraf
telegraf_agent_package_state: present
telegraf_agent_hostname: "{{ inventory_hostname }}"
telegraf_agent_interval: 10
telegraf_agent_debug: False
telegraf_agent_round_interval: True
telegraf_agent_flush_interval: 10
telegraf_agent_flush_jitter: 0
telegraf_agent_aws_tags: False
telegraf_agent_aws_tags_prefix: ""

# v0.13 settings (not sure if supported in older version):
telegraf_agent_collection_jitter: 0
telegraf_agent_metric_batch_size: 1000
telegraf_agent_metric_buffer_limit: 10000
telegraf_agent_quiet: False

# v1.1 settings:
telegraf_agent_logfile: ""
telegraf_agent_omit_hostname: False


telegraf_global_tags:
  - tag_name: hoster
    tag_value: "{{inventory_hostname}}"
    
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{influxIp}}"]
      - database = "{{influxDatabase}}"
      - precision = "s"

# defaults - /etc/telegraf/telegraf.conf
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: io
  - plugin: mem
  - plugin: net
  - plugin: system
  - plugin: swap
  - plugin: netstat
  - plugin: processes
  - plugin: kernel

# extra configuration - /etc/telegraf/telegraf.d/*
telegraf_plugins_extra: {}
telegraf_plugins_extra_exclusive: False

# RedHat specific settings for convenience
telegraf_redhat_releasever: "$releasever"

telegraf_win_install_dir: 'C:\Telegraf'
telegraf_win_logfile: 'C:\\Telegraf\\telegraf.log'
telegraf_win_include: 'C:\Telegraf\telegraf_agent.d'
telegraf_win_service_args:
  - -service install
  - -config {{ telegraf_win_install_dir }}\telegraf\telegraf.conf
  - --config-directory {{ telegraf_win_include }}
