---

- name: "Debian | Set name if state == latest"
  set_fact:
    telegraf_agent_package: telegraf={{ telegraf_agent_version }}-{{ telegraf_agent_version_patch }}
  when:
    - telegraf_agent_package_state != "latest"

- name: "Debian | Ensure the system can use the HTTPS transport for APT"
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: "Debian | Install APT HTTPS transport"
  apt:
    name: "apt-transport-https"
    state: present
  when:
    - not apt_https_transport.stat.exists
  become: yes

- name: "Debian | Download Telegraf apt key"
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    id: 2582E0C5
    state: present
  become: yes

- name: "Debian | Add Telegraf repository (using LSB)"
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable"
    filename: "telegraf"
    state: present
  become: yes
  when:
    - ansible_lsb is defined
    - ansible_lsb.codename is defined

- name: "Debian | Add Telegraf repository"
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    filename: "telegraf"
    state: present
  become: yes
  when:
    - ansible_lsb is not defined or ansible_lsb.codename is not defined

- name: "Debian | Install telegraf package"
  apt:
    name: "{{ telegraf_agent_package }}"
    state: "{{ telegraf_agent_package_state }}"
    force: True
  notify: "Restart Telegraf"
  become: yes
