---
# description: RedHat specific installation

- name: "RedHat | Set name if state == latest"
  set_fact:
    telegraf_agent_package: telegraf-{{ telegraf_agent_version }}
  when:
    - telegraf_agent_package_state != "latest"

- name: Use RHEL 7 packages for Fedora
  set_fact:
    telegraf_redhat_releasever: 7
  when: ansible_distribution == "Fedora"

- name: "RedHat | Add yum repository"
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: "https://repos.influxdata.com/rhel/{{ telegraf_redhat_releasever }}/$basearch/stable"
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: "RedHat | Install telegraf package"
  package:
    name: "{{ telegraf_agent_package }}"
    state: "{{ telegraf_agent_package_state }}"
  notify: "Restart Telegraf"
