---
# handlers file for ansible-telegraf

- name: "Restart Telegraf"
  service:
    name: telegraf
    state: restarted
    enabled: yes
  become: yes

- name: "Restart Windows Telegraf"
  win_service:
    name: Telegraf
    start_mode: auto
    state: restarted
