---
# tasks file for ansible-telegraf

- name: "Install on RedHat"
  include_tasks: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"

- name: "Install on Debian"
  include_tasks: "Debian.yml"
  when:
    - ansible_os_family == "Debian"
  tags:
    - telegraf
    - packages

- name: "Install on Suse"
  include_tasks: "Suse.yml"
  when: ansible_os_family == "Suse"

- name: "Configure telegraf"
  include_tasks: "configure_linux.yml"
  when:
    - ansible_os_family != "Windows"

- name: "Install / Configure telegraf on Windows"
  include_tasks: "configure_windows.yml"
  when:
    - ansible_os_family == "Windows"
